// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_Commerce.Data;

#nullable disable

namespace eCommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209205401_AddBasketItemsToDb")]
    partial class AddBasketItemsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("e_Commerce.Data.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("e_Commerce.Data.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("e_Commerce.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1387),
                            Description = "This is our 1st Product",
                            IsDeleted = false,
                            Name = "1st Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 10000L,
                            QuantityInStock = 100,
                            Type = "Sports"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1390),
                            Description = "This is our 2nd Product",
                            IsDeleted = false,
                            Name = "2nd Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 20000L,
                            QuantityInStock = 200,
                            Type = "Sports2"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1391),
                            Description = "This is our 4th Product",
                            IsDeleted = false,
                            Name = "4th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 40000L,
                            QuantityInStock = 400,
                            Type = "Sports4"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1393),
                            Description = "This is our 5th Product",
                            IsDeleted = false,
                            Name = "5th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 50000L,
                            QuantityInStock = 500,
                            Type = "Sports5"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1395),
                            Description = "This is our 6th Product",
                            IsDeleted = false,
                            Name = "6th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 60000L,
                            QuantityInStock = 600,
                            Type = "Sports6"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1396),
                            Description = "This is our 7th Product",
                            IsDeleted = false,
                            Name = "7th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 70000L,
                            QuantityInStock = 700,
                            Type = "Sports7"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1398),
                            Description = "This is our 8th Product",
                            IsDeleted = false,
                            Name = "8th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 80000L,
                            QuantityInStock = 800,
                            Type = "Sports8"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1399),
                            Description = "This is our 9th Product",
                            IsDeleted = false,
                            Name = "9th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 90000L,
                            QuantityInStock = 900,
                            Type = "Sports9"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1401),
                            Description = "This is our 10th Product",
                            IsDeleted = false,
                            Name = "10th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 100000L,
                            QuantityInStock = 1000,
                            Type = "Sports10"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1403),
                            Description = "This is our 11th Product",
                            IsDeleted = false,
                            Name = "11th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 110000L,
                            QuantityInStock = 1100,
                            Type = "Sports11"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1404),
                            Description = "This is our 12th Product",
                            IsDeleted = false,
                            Name = "12th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 120000L,
                            QuantityInStock = 1200,
                            Type = "Sports12"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Adidas",
                            CreationTime = new DateTime(2022, 12, 9, 20, 54, 1, 512, DateTimeKind.Utc).AddTicks(1406),
                            Description = "This is our 13th Product",
                            IsDeleted = false,
                            Name = "13th Product",
                            PictureURL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adidas.ca%2Fen%2Fwomen-superstar&psig=AOvVaw12H4_Aokgc686UoNzG7nMk&ust=1669258458275000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMj0172mw_sCFQAAAAAdAAAAABAE",
                            Price = 130000L,
                            QuantityInStock = 1300,
                            Type = "Sports13"
                        });
                });

            modelBuilder.Entity("e_Commerce.Data.BasketItem", b =>
                {
                    b.HasOne("e_Commerce.Data.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_Commerce.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_Commerce.Data.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
